# Generated by Django 2.2.16 on 2022-10-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_FOLLOWCONSTRAINS'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_self_subscribe',
        ),
    ]
