# Generated by Django 2.2.16 on 2022-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_FOLLOWCONSTRAINSDELETE'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='unique subscription'),
        ),
    ]
